### ISSUE TITLE
Doc request: compare semverver

### ISSUE THREAD

**Issue by CAD97** [obi1kenobi/cargo-semver-check#21]
[semverver](https://lib.rs/crates/semverver) is another tool for checking semver violations. Its approach at a high level is to compare rlibs rather than rustdocs.

semverver was originally published as part of GSoC 2017, but has recently been adopted into the rust-lang org to hopefully keep it functional.

Obviously there will be differences in what changes both tools do and don't catch, and keeping a scorecard of that probably isn't really worth the effort. It would be nice, however, to call out semverver as an alternative and list some high-level differences resulting from the different approaches. As an initial intuition, that would include at least

- semver-checks by design only checks rustdoc-exposed information, so ignores any `#[doc(hidden)]` items, which semverver has access to to check.
- semver-checks works off of (mostly?) stable metadata from rustdoc; semverver is by design tied to only work on a specific nightly.

Personally, I think diffing the documented surface *is* the "more correct" approach here, as semver is about public exposed API. Relying on details not contained in the documentation is relying on details outside of the semver guarantee.

**Comment by obi1kenobi** [comment]
Thanks for the suggestion and for the thoughtful writeup! I think it's a good idea and very worth doing.

I've heard of but have never used `semverver`, and I have only a very shallow understanding of the technique it uses and its tradeoffs. Due to my unfamiliarity, I'm concerned that I might not be able to provide a meaningful and fair comparison.

I'd also like to compare `cargo-semver-checks` to `cargo-public-api`, another tool with yet another approach to the problem of semver-checking. That one I'm more familiar with and I would feel more comfortable writing about.

@CAD97, have you used `semverver`? Would you be interested in giving PR feedback or collaborating on the comparison docs?

**Comment by CAD97** [comment]
I haven't really tried using semverver myself either, so I won't be much help there unfortunately. But what I think is more worth documenting is the high-level differences implied by the technique, rather than implementation, anyway.

I'd be happy to review a PR adding the comparison.

**Comment by obi1kenobi** [comment]
Thanks, I'll try to put something together and run it by you. I'll be travelling so it might be a couple of weeks.
