### ISSUE TITLE
Make default baseline the previous stable version in the registry

### ISSUE THREAD

**Issue by epage** [obi1kenobi/cargo-semver-check#55]
With just `cargo semver-checks` in package directory, it should take the current version and select the previous one.  For pre-release versions, it should select the previous non-pre-release as breaking changes between prereleases is fine.

**Comment by obi1kenobi** [comment]
For other folks reading this issue: this logic is [already implemented in the GitHub Action](https://github.com/obi1kenobi/cargo-semver-checks-action) that runs `cargo-semver-checks`.

This issue is about moving some of that functionality into `cargo-semver-checks` itself to make it easier to run the tool directly via the CLI, as opposed to running it as a GitHub Action.

**Comment by epage** [comment]
Is the action correctly handling pre-release?  imo the default should not select a previous pre-release but the previous stable release

**Comment by obi1kenobi** [comment]
Good question. Agreed on the desired behavior. Have not tested it but I'd guess it would pick pre-releases like so:
- `1.2.3-alpha.1` would compare to `1.2.2`
- `1.2.3-alpha.2` would compare to `1.2.3-alpha.1`
- `1.2.3` would compare to `1.2.3-alpha.2`

I believe this produces an equivalent result because semver-checking is transitive: if all those transitions are individually valid then `1.2.3` compared to `1.2.2` is valid too. But probably still worth changing when moving the logic into `cargo-semver-checks` itself.

**Comment by epage** [comment]
Expected result
- `1.2.3-alpha.1` should compare to `1.2.2`
- `1.2.3-alpha.2` should compare to `1.2.2`
- `1.2.3` should compare to `1.2.2`

Unfortunately, it is not transitive for pre-release because you are allow to make breaking changes between pre-release versions.

**Comment by epage** [comment]
https://github.com/obi1kenobi/cargo-semver-check/pull/92 fixed some related pre-release issues
