### ISSUE TITLE
Re-license as Apache/MIT?

### ISSUE THREAD

**Issue by epage** [obi1kenobi/cargo-semver-check#84]
Cargo is dual-licensed so I assume dual licensing will make it easier to merge.  The sooner, the better to get buy-in from all copyright holders (ie contributors)

**Note::** I am speaking from a position of ignorance on licensing

**Comment by obi1kenobi** [comment]
Dual-licensing `cargo-semver-checks` and its GitHub Action is fine by me.

Would merging into cargo require all dependencies of `cargo-semver-checks` to be Apache/MIT as well, or can dependencies (e.g. `trustfall`) remain Apache 2.0? Because that might be trickier and would probably require more work and more conversations.

**Comment by epage** [comment]
The cargo code base itself is Apache/MIT.  I am not aware of any part of it that has a different license.

I do not know the state of dependencies.

I also do not know how much the rust project cares one way or the other.  This is speculative to remove possible snags from the path to stablization sooner when they are easier to deal with

**Comment by obi1kenobi** [comment]
I'm inclined to complete this this week, while the only commits to the main branch are yours and mine. I'm fine with just mirroring cargo's approach and including both licenses in the repo named `LICENSE-APACHE` and `LICENSE-MIT`, then updating `Cargo.toml` to match.

Do you have a preference between you or me taking this task? Either is fine by me.

**Comment by epage** [comment]
I'm ok either way
